<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="Event_Managment.Home" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <h1>Events</h1>
        <p class="lead">Below are the Events.</p>
        
    </div>
    <%-- Upcoming events--%>
    <div class="row">
         <div class="col-md-4">
            <h2>Upcoming Events </h2>
            <asp:PlaceHolder runat="server" ID="PlaceHolder1"></asp:PlaceHolder>
            <asp:ListView ID="ListView2" runat="server">
                <LayoutTemplate>
                    <table id="Table1" runat="server" class="TableCSS">
                        <tr id="Tr1" runat="server" class="TableHeader">
                            <td width="200" id="Td1" runat="server">Title</td>
                            <td width="600" id="Td2" runat="server">Startdate</td>
                            <td width="200" id="Td3" runat="server">Duration</td>
                            <td  width="200" id="Td4" runat="server">Author</td>
                            <td width="200" id="Td5" runat="server">location</td>
                        </tr>
                        <tr id="ItemPlaceholder" runat="server">
                        </tr>
                    </table>
                </LayoutTemplate>
                <ItemTemplate>
                    <tr runat="server" class="TableData">
                        <td width="50">
                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("title")%>'>
                            </asp:Label>
                        </td>
                         <td width="600">
                            <asp:Label ID="Label2" runat="server" Text='<%# Convert.ToDateTime(Eval("sdate")).ToString("dd/MM/yyyy") %>'>
                            </asp:Label>
                        </td>
                         <td width="50">
                            <asp:Label ID="Label3" runat="server" Text='<%# Eval("duration")%>'>
                            </asp:Label>
                        </td>
                        <td width="100">
                            <asp:Label ID="Label4" runat="server" Text='<%# Eval("author")%>'>
                            </asp:Label>
                        </td>
                        <td width="100">
                            <asp:Label ID="Label5" runat="server" Text='<%# Eval("location")%>'>
                            </asp:Label>
                        </td>
                        <td width="200">
                            <asp:Button runat="server" ID="VD" OnClick="Unnamed1_Click" Text="View Details&raquo; "></asp:Button>
                        </td>
                    </tr>
                </ItemTemplate>
            </asp:ListView>
        </div>
    </div>
    <%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
    <style type="text/css">
        .modalPopup {
            background-color: #FFFFFF;
            width: 800px;
            border: 3px solid #0DA9D0;
            height: 450px;
        }
            .modalPopup .header {
                background-color: #2FBDF1;
                height: 30px;
                color: white;
                line-height: 30px;
                text-align: center;
                font-weight: bold;
            }
            .modalPopup .footer {
                padding: 3px;
            }
    </style>
    <p>
        <asp:Label ID="Label6" runat="server"></asp:Label>
    </p>
    <ajaxToolkit:ModalPopupExtender ID="mpe2" PopupControlID="Panel2" TargetControlID="Label6" CancelControlID="CLosebtn" runat="server"></ajaxToolkit:ModalPopupExtender>
    <asp:Panel ID="Panel2" runat="server" CssClass="modalPopup">
        
        <div id="divdetail" align="center">
            <asp:GridView OnRowDataBound="GridView2_RowDataBound" ID="GridView2" AutoGenerateColumns="false" AutoGenerateEditButton="true" OnRowEditing="OnRowEditing1" OnRowUpdating="OnRowUpdating1" OnRowCancelingEdit="OnRowCancelingEdit1" AutoGenerateDeleteButton="true" OnRowDeleting="OnRowDeleting1" DataKeyNames="id"  runat="server" CellPadding="3" Height="353px" Width="669px" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px">
               <Columns>
                           <asp:BoundField DataField="title" HeaderText="Title" />
                           <asp:BoundField DataField="sdate" HeaderText="Start date" />
                           <asp:BoundField DataField="duration" HeaderText="Duration" />
                           <asp:BoundField DataField="author" HeaderText="Author" />
                           <asp:BoundField DataField="location" HeaderText="Location" />
                           </Columns>
                <FooterStyle BackColor="White" ForeColor="#000066" />
                <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                <PagerStyle ForeColor="#000066" HorizontalAlign="Left" BackColor="White" />
                <RowStyle ForeColor="#000066" />
                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#007DBB" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#00547E" />
            </asp:GridView>
        </div>
        <div id="footerdiv1" class="footer" align="center">
            <asp:Button ID="Button1" runat="server" Text="Close" Height="47px" Width="103px" />
        </div>
    </asp:Panel>

       <%-- past events--%>
        <div class="col-md-4">
            <h2>Passed Events </h2>
            <asp:PlaceHolder runat="server" ID="pastE"></asp:PlaceHolder>
            
            <asp:ListView ID="ListView1" runat="server">
                <LayoutTemplate>
                    <table id="Table1" runat="server" class="TableCSS">
                        <tr id="Tr1" runat="server" class="TableHeader">
                            <td width="200" id="Td1" runat="server">Title</td>
                            <td width="600" id="Td2" runat="server">Startdate</td>
                            <td width="200" id="Td3" runat="server">Duration</td>
                            <td  width="200" id="Td4" runat="server">Author</td>
                            <td width="200" id="Td5" runat="server">location</td>
                        </tr>
                        <tr id="ItemPlaceholder" runat="server">
                        </tr>
                    </table>
                </LayoutTemplate>
                <ItemTemplate>
                    <tr runat="server" class="TableData">
                        <td width="50">
                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("title")%>'>
                            </asp:Label>
                        </td>
                         <td width="600">
                            <asp:Label ID="Label2" runat="server" Text='<%# Convert.ToDateTime(Eval("sdate")).ToString("dd/MM/yyyy") %>'>
                            </asp:Label>
                        </td>
                         <td width="50">
                            <asp:Label ID="Label3" runat="server" Text='<%# Eval("duration")%>'>
                            </asp:Label>
                        </td>
                        <td width="100">
                            <asp:Label ID="Label4" runat="server" Text='<%# Eval("author")%>'>
                            </asp:Label>
                        </td>
                        <td width="100">
                            <asp:Label ID="Label5" runat="server" Text='<%# Eval("location")%>'>
                            </asp:Label>
                        </td>
                        <td width="200">
                            <asp:Button runat="server" ID="VD" OnClick="Unnamed_Click" Text="View Details&raquo; "></asp:Button>
                        </td>
                    </tr>
                </ItemTemplate>
            </asp:ListView>
        </div>
    
    <%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
    <style type="text/css">
        .modalPopup {
            background-color: #FFFFFF;
            width: 800px;
            border: 3px solid #0DA9D0;
            height: 450px;
        }
            .modalPopup .header {
                background-color: #2FBDF1;
                height: 30px;
                color: white;
                line-height: 30px;
                text-align: center;
                font-weight: bold;
            }
            .modalPopup .footer {
                padding: 3px;
            }
    </style>
    <p>
        <asp:Label ID="Lblpopup" runat="server"></asp:Label>
    </p>
    <ajaxToolkit:ModalPopupExtender ID="mpe" PopupControlID="Panel1" TargetControlID="Lblpopup" CancelControlID="CLosebtn" runat="server"></ajaxToolkit:ModalPopupExtender>
    <asp:Panel ID="Panel1" runat="server" CssClass="modalPopup">
        <div id="headerdiv" class="header">Events</div>
        <div id="divdetails" align="center">
            <asp:GridView OnRowDataBound="GridView1_RowDataBound" ID="GridView1" AutoGenerateColumns="false" AutoGenerateEditButton="true" OnRowEditing="OnRowEditing" OnRowUpdating="OnRowUpdating" OnRowCancelingEdit="OnRowCancelingEdit" AutoGenerateDeleteButton="true" OnRowDeleting="OnRowDeleting" DataKeyNames="id"  runat="server" CellPadding="3" Height="353px" Width="669px" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" >
               <Columns>
                           <asp:BoundField DataField="title" HeaderText="Title" />
                           <asp:BoundField DataField="sdate" HeaderText="Start date" />
                           <asp:BoundField DataField="duration" HeaderText="Duration" />
                           <asp:BoundField DataField="author" HeaderText="Author" />
                           <asp:BoundField DataField="location" HeaderText="Location" />
                           </Columns>
                <FooterStyle BackColor="White" ForeColor="#000066" />
                <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                <PagerStyle ForeColor="#000066" HorizontalAlign="Left" BackColor="White" />
                <RowStyle ForeColor="#000066" />
                <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#007DBB" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#00547E" />
            </asp:GridView>
        </div>
        <div id="footerdiv" class="footer" align="center">
            <asp:Button ID="CLosebtn" runat="server" Text="Close" Height="47px" Width="103px" />
        </div>
    </asp:Panel>
    </div>
</asp:Content>