<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="Event_Managment.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:GridView ID="GridView1" runat="server" DataKeyNames="id" OnRowDeleting="OnRowDeleting"  EmptyDataText="No records has been added." AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowEditing="OnRowEditing" OnRowUpdating="OnRowUpdating" OnRowCancelingEdit="OnRowCancelingEdit">
</asp:GridView>
</asp:Content>
